# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    yt.client:
        class: AppBundle\Services\YoutubeClient
        arguments: ["%oauth_file%"]
        calls:
            - [ setLogger, ["@logger"]]
            - [ setDoctrine, ["@doctrine"]]
            - [ setAuthChecker, ['@security.authorization_checker']]
            - [ setTokenStorage, ['@security.token_storage']]
            - [ setRouter, ['@router']]
