services:
    yt.client:
        class: AppBundle\Services\YoutubeClient
        arguments: ["%oauth_file%"]
        calls:
            - [ setLogger, ["@logger"]]
            - [ setDoctrine, ["@doctrine"]]
            - [ setAuthChecker, ['@security.authorization_checker']]
            - [ setTokenStorage, ['@security.token_storage']]
            - [ setRouter, ['@router']]
